name: CICD

on:
  push:
    branches:
      - main
    path-ignore:
      - 'helm/**'
      - 'k8s/**'
jobs:
  build:
    run-on:
    
    steps:
    - name: checkoutstage
      uses: actions/checkout@v4use
      with:
        path: main
    - name: Set up-Go env
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - run: go version

    - name: Build-phase
      uses: go build -o go
    
    - name: test
      uses: go test
